### ISSUE TITLE
getData failed, thrift exception on centos

### ISSUE THREAD

**Issue by colerowen** [facebookincubator/beringei#40] opened 2017-04-19 08:01 UTC
calling getData() by multithread(Each thread uses its own client) on centos will raise this error 。 There's no such problem on Ubuntu。
Is there any other reason that will cause this error?

**Comment by jteller** [comment] 2017-04-19 15:07
I really don't know, as we've only tested on Ubuntu 16.10

This seems like something may be broken with the thrift server or client.

**Comment by linuxfood** [comment] 2017-04-19 20:36
@colerowen  Can you provide us with some more data on the problem? For instance, are the client and server on the same machine? The same network? If possible a stack trace showing where in Beringei client this gets thrown would be helpful, as would any logs from the Beringei server (which may have some information like if thrift terminated the connection for some reason.)

This exception means that the underlying connection has some kind of problem and comes from thrift, which is known to work correctly on CentOS.

**Comment by colerowen** [comment] 2017-04-20 03:33
client and server are on the same network.  
When this error is raised on client ,  theres is nothing in log on the Beringei server.

**Comment by colerowen** [comment] 2017-04-20 03:50
besides, putDataPoints also raises this error ,but not as frequent as getData :
E0420 11:15:10.977551 15714 BeringeiNetworkClient.cpp:129] putDataPoints Failed. Reason: apache::thrift::transport::TTransportException: Channel is !good()

**Comment by linuxfood** [comment] 2017-04-28 20:21
Hi @colerowen the issue with `putDataPoints` looks similar in that it seems as though there isn't an active connection. The fact that the server doesn't say anything as well supports that. Are you able to use the standalone `beringei_put` and `beringei_get` utilities to talk to the server? Have you made sure that your clients are using the right configuration? We use glog for logging, so you may also want to try adding `-v=5` or so to your client and the server you're running for (a lot) of additional debugging information.

**Comment by colerowen** [comment] 2017-05-08 10:31
beringei_put and beringei_get works fine, and clients  are using the right configuration because this error occured after running for a while. 
i add -v=5 to client and server, and the server still doesn't say anything  when this error occurs in client.

**Comment by linuxfood** [comment] 2017-05-08 20:44
@colerowen OK, that's interesting. To help, we'll definitely need some more information. Anything you could provide about the circumstances of the failure to help us reproduce it locally would be great. Even better of course would be if you could share some simplified code that reproduces the issue.

Can you try running the client and/or server with `-v=7`? It looks like some of the debugging information on socket state may actually be up that high, based on some examination of: https://github.com/facebook/folly/blob/master/folly/io/async/AsyncSocket.cpp

The amount of information is going to be quite copious at that vlog level, so redirecting stderr/stdout to a file would be prudent.

**Comment by colerowen** [comment] 2017-05-09 09:30
I tried -v=7,  but nothing new appears.
log in client:
E0509 17:25:47.611810 10536 BeringeiNetworkClient.cpp:203] getData failed. Reason: apache::thrift::transport::TTransportException: Channel is !good()

log in server:
I0509 17:29:56.694855 27410 FunctionScheduler.cpp:370] Now running file-poller
I0509 17:29:57.211751 27412 FunctionScheduler.cpp:370] Now running updateMemoryStats

**Comment by colerowen** [comment] 2017-05-09 09:35
the exact same client code works fine in ubuntu.

**Comment by linuxfood** [comment] 2017-05-09 20:35
@colerowen Trying to debug platform issues (Ubuntu vs. CentOS) is challenging over a Github issue. There are a lot of configuration differences between the two at the system level: the network stacks are tuned differently, different firewall configurations, different system libraries, and more that could certainly be messing something up. Too many for us to be able to help on that alone. For what it's worth, our internal usage of Beringei runs on CentOS, so, we know the issue is not intrinsic to the platform. Focusing our efforts on isolating the root cause of the channel going bad (a timeout, an error, something else) should be more fruitful and will help guide us in understanding what specifically is different, rather than trying to reproduce it blindly.

Some more questions:
* Are the `-v=` settings really not producing any more detailed information? There should be a lot of information in the log at `-v=7`. Details about sockets opening and closing. This could mean that gflags and glog weren't built together in the right way.
* How long does it take for the issue to show up? (order of magnitude is fine, "minutes", "hours")
* Can you share some more details about what you're building?
* Does it reproduce if you get rid of the multi-threading?
* Does it reproduce if you put the client and server on the same machine?
* Does it reproduce if you strip out everything from your test case except some threads, and clients? (i.e., what's your minimal repro case?)
* Does it still reproduce if you build Beringei from trunk? We've made some changes since you opened the issue, though I don't see any commits that look related to this kind of problem.

**Comment by colerowen** [comment] 2017-05-10 05:10
using -v=7 now works for client, log as follows:
I0510 11:48:34.218888 17599 EventBase.cpp:166] EventBase(): Created.
I0510 11:48:34.218910 17599 AsyncSocket.cpp:190] new AsyncSocket(0x7f8014001b10, evb=0x7f80140014a0)
I0510 11:48:34.218924 17599 AsyncSocket.cpp:392] AsyncSocket::connect(this=0x7f8014001b10, evb=0x7f80140014a0, fd=7, host=192.168.0.13:9999
I0510 11:48:34.221463 17599 AsyncSocket.cpp:2006] AsyncSocket(this=0x7f8014001b10, fd=7, state=1 host=192.168.0.13:9999): failed while connecting in connect(): AsyncSocketExcep
tion: connect failed (immediately), type = Socket not open, errno = 99 (Cannot assign requested address)
I0510 11:48:34.221707 17599 AsyncSocket.cpp:558] AsyncSocket::setReadCallback() this=0x7f8014001b10, fd=-1, callback=0, state=4
I0510 11:48:34.221729 17599 Cpp2Channel.cpp:208] Channel is !good() in sendMessage
I0510 11:48:34.221755 17599 AsyncSocket.cpp:558] AsyncSocket::setReadCallback() this=0x7f8014001b10, fd=-1, callback=0, state=4
E0510 11:48:34.221783 17599 BeringeiNetworkClient.cpp:203] getData failed. Reason: apache::thrift::transport::TTransportException: Channel is !good()
I0510 11:48:34.221818 17599 AsyncSocket.cpp:558] AsyncSocket::setReadCallback() this=0x7f8014001b10, fd=-1, callback=0, state=4
I0510 11:48:34.221832 17599 Cpp2Channel.cpp:193] Got an EOF on channel
I0510 11:48:34.221854 17599 AsyncSocket.cpp:871] AsyncSocket::closeNow(): this=0x7f8014001b10, fd_=-1, state=4, shutdownFlags=6
I0510 11:48:34.221901 17599 AsyncSocket.cpp:248] AsyncSocket::destroy(this=0x7f8014001b10, evb=0x7f80140014a0, fd=-1, state=4
I0510 11:48:34.221912 17599 AsyncSocket.cpp:871] AsyncSocket::closeNow(): this=0x7f8014001b10, fd_=-1, state=4, shutdownFlags=6
I0510 11:48:34.221917 17599 AsyncSocket.cpp:242] actual destruction of AsyncSocket(this=0x7f8014001b10, evb=0x7f80140014a0, fd=-1, state=4)

**Comment by colerowen** [comment] 2017-05-10 05:12
it reproduced when i runned single-threading,  channel error still appeared from time to time.

**Comment by linuxfood** [comment] 2017-05-12 06:35
So, this is the relevant bit from the logs:
```
I0510 11:48:34.218924 17599 AsyncSocket.cpp:392] AsyncSocket::connect(this=0x7f8014001b10, evb=0x7f80140014a0, fd=7, host=192.168.0.13:9999
I0510 11:48:34.221463 17599 AsyncSocket.cpp:2006] AsyncSocket(this=0x7f8014001b10, fd=7, state=1 host=192.168.0.13:9999): failed while connecting in connect(): AsyncSocketExcep
tion: connect failed (immediately), type = Socket not open, errno = 99 (Cannot assign requested address)
```

The error _"Cannot assign requested address"_ means that something is going on at the network layer, which kind of out of scope for us helping you. I'd check that at least all the sockets that are being opened are getting closed to ensure that you're not exhausting the available sockets on the machine (which seems likely, since these file descriptor numbers are pretty low), and that the Ubuntu and CentOS machines are configured to have the same network address space. E.g., All the addresses are from CIDR 192.168.0.0/16, and that the server is listening on the expected address, and that the client has a route to that address, etc. Beyond that I'm not sure how much more we can help. This currently doesn't really look like a Beringei issue, as it does a system issue.

**Comment by linuxfood** [comment] 2018-01-04 08:39
I'm going to assume that this was resolved and close it out. Let us know if we can help further.

**Closed by linuxfood** 2018-01-04 08:39 UTC
